[package]
name = "proof_utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ark-bn254 = "0.5.0"
ark-serialize = "0.5.0"
wasm-bindgen = {version = "0.2.100", features = ["serde-serialize"]}

[features]
default = []
console_error_panic_hook = []
